// the definition of IOCTL command

#ifndef __FIRSTCHARDEVDRIVERIOCTL_H__
#define __FIRSTCHARDEVDRIVERIOCTL_H__

#define FCDDIOCTL_IOCMD_CONTROL		0x80
#define FCDDIOCTL_IOCMD_READ		0x81
#define FCDDIOCTL_IOCMD_WRITES		0x82
#define FCDDIOCTL_IOCMD_WRITEM		0x83
#define FCDDIOCTL_IOCMD_WRITEREAD	0x84

#define FCDDIOCTL_MAGIC	'i'

#define FCDDIOCTL_NR_MIN	FCDDIOCTL_IOCMD_CONTROL
#define FCDDIOCTL_NR_MAX	FCDDIOCTL_IOCMD_WRITEREAD

#define FCDDIOCTL_CONTROL	_IO(FCDDIOCTL_MAGIC, FCDDIOCTL_IOCMD_CONTROL)
#define FCDDIOCTL_READ		_IOR(FCDDIOCTL_MAGIC, FCDDIOCTL_IOCMD_READ, unsigned long)
#define FCDDIOCTL_WRITES	_IOW(FCDDIOCTL_MAGIC, FCDDIOCTL_IOCMD_WRITES, unsigned long)
#define FCDDIOCTL_WRITEM	_IOW(FCDDIOCTL_MAGIC, FCDDIOCTL_IOCMD_WRITEM, unsigned char [50])
#define FCDDIOCTL_WRITEREAD	_IOWR(FCDDIOCTL_MAGIC, FCDDIOCTL_IOCMD_WRITEREAD, unsigned long)

#endif

